package com.loyalty.auth0.proxy.components.constant

class Constants {

    final static String RSA = "RSA"
    final static String UTF_8 = "UTF-8"
    final static String USER_ID_PREFIX_CREATE = "EMAIL-"
    final static String TYPE_EMAIL = "Email"
    final static String USER_ID_PREFIX_GET_INFO = "auth0|"

    final static DEFAULT_CONNECTION_CREATE_DATA = "member-email-idp"
    final static EXPIRED_GET_INFO_TOKEN = "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlJVTkZNRVF4UXpVNVF6YzJNemN3UlVKR01qTTVRall5TXpFNVJFWXpOVFUyUlVNM01qUkZSZyJ9.eyJpc3MiOiJodHRwczovL29hdXRoLWRldi5haXJtaWxlcy5jYS8iLCJzdWIiOiJubTBxWkIwME0xWXA1S09MZWE3aHVCZzBXczNwbWZSdEBjbGllbnRzIiwiYXVkIjoiYWlybWlsZXMtd2ViLWNvbGxlY3RvciIsImlhdCI6MTYxNDgwNDY5MywiZXhwIjoxNjE0ODkxMDkzLCJhenAiOiJubTBxWkIwME0xWXA1S09MZWE3aHVCZzBXczNwbWZSdCIsInNjb3BlIjoiYXV0aDA6cmVhZCBhdXRoMDp3cml0ZSIsImd0eSI6ImNsaWVudC1jcmVkZW50aWFscyJ9.e0K1_zUyw_H6xJCMjFunvQixNX-9Ni5L7kAuPTg2pXlVQfizTjqAiuoSHaLi8phOcJ43N3uHqrIIyys-cTLOJVpVJJ9WEl7q5x-VQK7ukpfTIoNhY54MaUjcSsvGq0yk5WhOVIjnbNJD8nBsQaA_S_CKGk0fkKv1df8C-JqTP4lx-UF8-VVEQ-HoneU6oRVIzA2UQTREtV9wRObfz4lDa_yiAt7gFb_FWLApKe7N7Rk0GU87gYNSt4cwhfqWttHWX2bX3Ji7y5lMzYmUABcf_3Czq70jHxPmGTNB5wo3sq_Hda-47y0iXAlF1xRqN07eVmTHaYC5Jb6yOcjwLkOadQ"
}
